### ISSUE TITLE
New feature proposal: temperature offset

### ISSUE THREAD

**Issue by kozerskil** [daenny/climate_group#10]
I have 2 thermostats in 1 room, however one of them should be set to lower temperature. It would be nice to have a possibility to configure the offset for all of the thermostats.

**Comment by daenny** [comment]
How would you then like to have the setpoint temperature shown? Should it be the average, or the `adjusted average`?

**Comment by daenny** [comment]
Also this would mean that we need to change the method how the calls are made. At the moment only one service call is made to set the temperature etc, with the list of all entities, if you have offsets you would need to make one service call per entity.

**Comment by kozerskil** [comment]
I think there should be one "master", eg. first entity, and the temperature shown is master temperature. Regarding many call, I don't think it is an issue: how many thermostats there can be in single group? And there might be some logic, grouping all thermostats with the same temperature, and one call made per subgroup. Not sure if it's not overcomplicated, but for me it would be valuable.

**Comment by blademckain** [comment]
the master slave functionality could be easily solved if you could choose whether to fill the component automatically or manually. Example of code:
```yaml
climate:
  - platform: climate_group
    name: 'Climate Friendly Name'
    temperature_unit: C  
    entities:
    - climate.clima1
    - climate.clima2
    load: automatic or manual
    preset:
      -name: home
        target_temperature_low: 20
        target_temperature_high: 25
      -name: away
       target_temperature_low: 16
       target_temperature_high: 18
     hvac_modes: HVAC_MODE_OFF, HVAC_MODE_HEAT
     fan_modes: FAN_ON, FAN_OFF
....
   *other properties from https://developers.home-assistant.io/docs/core/entity/climate/
....
```

automatic: takes all the characteristics of the other climates
manual:  creates a climate component with only those characteristics (obviously they must be compatible with the other climates)
