### ISSUE TITLE
hvac_action issue?

### ISSUE THREAD

**Issue by sebastien-k** [daenny/climate_group#12]
Hi,

My hvac_action attribute from the climate_group is always "heating" when turned on, even if the target temperature is reached. It should be "Idle", as are his "master" entities.

```yaml
  - platform: climate_group
    name: 'Thermostat Salon'
    entities:
    - climate.thermostat_salon_droit
    - climate.thermostat_salon_gauche

```

![image](https://user-images.githubusercontent.com/57752274/74076197-c864b300-4a16-11ea-887e-6e9d3ea08bdd.png)

Is is a bug, or I did something wrong?

Thank you for your help!
