### ISSUE TITLE
Plugin stopred working HA Update 0.107 -> 0.108.3

### ISSUE THREAD

**Issue by jaddel** [daenny/climate_group#18]
Is there any troubleshooting i can do?

**Comment by daenny** [comment]
Is there anything in the logs? I did not update yet. I will do this maybe this weekend.

**Comment by jaddel** [comment]
nothing obvious to me, wich log shall i look at?

**Comment by daenny** [comment]
Which version of this component are you running?

**Comment by jaddel** [comment]
Version: 0.1.2

Here is my log.

```
Platform error climate.climate - No module named 'homeassistant.components.climate.climate'
11:11:20 PM – Hass.io (ERROR)
```
```

Log Details (ERROR)
Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:269
Integration: Hass.io (documentation, issues)
First occurred: 11:11:20 PM (1 occurrences)
Last logged: 11:11:20 PM

Platform error climate.climate - No module named 'homeassistant.components.climate.climate'
```

**Comment by daenny** [comment]
Could it be that you maybe have accidentally changed your configuration? Can you please check your entries? The component is called ’climate_group’ not ’climate’. You can also test the newer beta versions / master.

**Comment by chrkoe** [comment]
I am new on this integration and installed it via HACS on 0.108.3 with no problems.
This is my part in the configuration.yaml (maybe it can help you identifying problems in your config).
```
climate:
  - platform: climate_group
    name: 'Heizung Wohnzimmer'
    entities:
    - climate.0x00158d0003abcdef_climate
    - climate.0x00158d0003abcde0_climate
  - platform: climate_group
    name: 'Heizung Esszimmer'
    entities:
    - climate.0x00158d0003abcde1_climate
    - climate.0x00158d0003abcde2_climate
```
