### ISSUE TITLE
More than one climate group. Howto?

### ISSUE THREAD

**Issue by luebbe** [daenny/climate_group#30]
I'm running HA 0.118.3 in Docker on a RPI 3.

How can I define more than one climate group?

I put the following into my configuration.yaml:
```
climate:
  - platform: climate_group
    name: 'Anbau Thermostat'
    entities:
    - climate.anbau_links
    - climate.anbau_rechts
  - platform: climate_group
    name: 'Dach Thermostat'
    entities:
    - climate.dach_links
    - climate.dach_rechts
```

But only the group "Anbau Thermostat" shows up in HA. Even when I reverse the order of the two groups and make "Dach Thermostat" the first. The four individual entities are visible in HA.
It makes no difference whether I restart HA via the GUI or via docker restart.
Where's my mistake?
