### ISSUE TITLE
Not working with AI_Thermostats

### ISSUE THREAD

**Issue by bruvv** [daenny/climate_group#45]
I am just corsslinking this since this is effected as well.
When using ai thermostat and this addon only 1 TRV will change temps:
issue: https://github.com/KartoffelToby/ai_thermostat/issues/68

**Comment by KartoffelToby** [comment]
just try to create a ai Thermostat for each real TRV and then groupe the ai TRVs

**Comment by bruvv** [comment]
I tried. Like mentioned. It doesn't work. Only the first trv will be adjusted.

**Comment by KartoffelToby** [comment]
Its working example conf:

```yaml
climate:
  - platform: ai_thermostat
    name: Ai - TRV - Office - 1
    thermostat: climate.real_trv_office_1
    temperature_sensor: sensor.temperatur_office_temperature
    window_sensors: group.office_windows
    weather: weather.home
    off_temperature: 20
    unique_id: 1
  - platform: ai_thermostat
    name: Ai - TRV - Office - 2
    thermostat: climate.real_trv_office_2
    temperature_sensor: sensor.temperatur_office_temperature
    window_sensors: group.office_windows
    weather: weather.home
    off_temperature: 20
    unique_id: 2
  - platform: climate_group
    name: "TRV - Office"
    temperature_unit: C
    entities:
      - climate.ai_trv_office_1
      - climate.ai_trv_office_2
```

this issue can be closed
