### ISSUE TITLE
More than one Climate group!

### ISSUE THREAD

**Issue by AngloYorkshire** [daenny/climate_group#51]
Is it possible to have more than one climate group?
For example, I want three...
1. All the TRV's in the house
2. All the Downstairs TRV's
3. All the Upstairs TRV's

Then I can put my upstairs heating on later in the evening before bed rather than warm the whole house when not needed.

Many thanks and keep up the good work.

**Comment by bjornsivertsen** [comment]
Yes, this is an example from my configuration:

```
climate:
  - platform: climate_group
    name: "Appartment Temperature"
    temperature_unit: C # default to celsius, 'C' or 'F'
    entities:
      - climate.dining_room_trv_thermostat
      - climate.bathroom_trv_thermostat
      - climate.living_room_trv1_thermostat
      - climate.living_room_trv2_thermostat
      - climate.bedroom_trv_thermostat

  - platform: climate_group
    name: "Common Area"
    temperature_unit: C # default to celsius, 'C' or 'F'
    entities:
      - climate.dining_room_trv_thermostat
      - climate.living_room_trv1_thermostat
      - climate.living_room_trv2_thermostat
      - climate.bathroom_trv_thermostat
```
