### ISSUE TITLE
Adding Unique ID to config

### ISSUE THREAD

**Issue by controlcde** [daenny/climate_group#61]
I want to add a unique id to my configuration to customize friendly name in HA UI after I read #52. My configuration is simple: 
```
- platform: climate_group
  name: 'Heizung | Kinderzimmer Thermostate'
  temperature_unit: 'C'
  entities:
  - climate.thermostat_kinderzimmer_l
  - climate.thermostat_kinderzimmer_r
```
How could I enter unique id in configuration or will it build automatically? And whats the nomenclature for a unique id?

**Comment by snigehere** [comment]
I would support this - in order to share the defined climate group with Alexa (via HA Voice assistant configuration), and set up an alias for the entity, I need to have a unique ID

![Snap10](https://github.com/daenny/climate_group/assets/104912027/afa92279-60ed-4ea1-985e-409ed42af03e)

**Comment by t-animal** [comment]
You need to install a beta version from hacs (I use 1.0.0-rc6), then change the config as following:

```
climate:
  - platform: climate_group
    name: 'Some Name'
    unique_id: some-uuid
    entities:
    - climate.yourtemp1
    - climate.yourtemp2
```

Instead of some-uuid you can put any uuid value from https://www.uuidgenerator.net/version4 . Just make sure you never re-use that value for another entity.
