### ISSUE TITLE
I can't turn off the climate group

### ISSUE THREAD

**Issue by DaN66O** [daenny/climate_group#63]
I have installed version 1.0.0-rc6
After that , I can't turn off the climate group
```
climate:
  - platform: climate_group
    name: radiator_children_group
    temperature_unit: C
    entities:
      - climate.radiator_children_left
      - climate.radiator_children_right
```
![Screenshot_30](https://user-images.githubusercontent.com/113509164/236903440-7065b50e-6a49-4c77-99d7-71a4867f7653.png)
I turn it off, and it turns on again
Although at the same time he turned off climate in the group
Maybe this error is because individual climates don't have the hvac_action attribute?
![Screenshot_31](https://user-images.githubusercontent.com/113509164/236905538-5a2809bb-a58e-4ef7-a296-4dac3afdef3e.png)
If you restart the Home Assistant at the same time, the climate group becomes unavailable.
And I can no longer include the climate group, only individually each entities.
