### ISSUE TITLE
Order of elements wildly mixed 

### ISSUE THREAD

**Issue by jtauscher** [daenny/climate_group#64]
Hi guys, the order of group elements seems to be random but only for the groups
```

entity: climate.ac_wz_ez
name: WZ & EZ
hide:
  state: true
  temperature: false
step_size: 1
control:
  hvac:
    'off':
      name: false
    auto:
      name: false
    cool:
      name: false
    heat:
      name: false
    dry:
      name: false
    fan_only:
      name: false
  fan:
    _hide_when_off: true
    auto:
      name: false
type: custom:simple-thermostat
layout:
  step: row
  mode:
    names: true
    headings: false
    icons: true
header:
  name: WZ + EZ

```

![image](https://github.com/daenny/climate_group/assets/45608914/cb57c425-11e0-4ed3-a8ba-81b0d6e19cd5)
